package day3

import (
	"strings"
)

var input = "RCMRQjLLWGTjnlnZwwnZJRZH\nqnvfhpSbvSppNddNdSqbbmmdPrwttJVrVPDVrJtHtwPZhrPJ\nBFpFzSSqSFFSvQsnWgCMjTLzng\nDbWVcVRRdlLffvtqjTWNgQ\nmJJMpsmrMrJSHJpsHrFHvBvgHvqfNvzffgTvfj\nmMhPjmjmFPJhMSGGcDRlwRdcLGPc\nqFcbmWFJqqWpRJcQWpqsQQQwSPCPrHRHCPdNZtSrSHwrNZ\njGMjGLhhhgTvghgtGVjnNCrPVwZSZffSNSwHZZdH\nDvzDlvvhnjlMlglglGGhDLpqqcJWWtsmszpWbBBBmQmb\nSPLPHQbJSbPsvTLmfDvVDctvWhcDlD\njdRRzzGgJqwrpMRMgdjlcVcWqfWWlfDlmmlWhB\nrwgRGdpGprNNLQLsbZJPsn\nGZhTVLztHrSzrRBz\nMJWjMvsfSCLSnrJn\nMjglcgWMdccvZGFtTDchLLLh\nrgDHBgBjRgRTgwzwthBnQwmBtB\nMsMpSfMsTGTFFLdFFFMFsnNmthNnzhthtwmWnznz\npZMpJdvJMGRHVJJTVHjb\nTQVqZVBcBBdBfbpN\nzvzrtCshrntCHslPMMMFpZHbNSpb\nhLWhGLttsvLvrrWvhzVmQgwJZTRcggTjGcgT\nSqRGLHtSbtNTbhjFTjDDpF\nWwgJgmdmMdwPDVQQBBhSBFwV\nJMPlmlSldWZmRqtLsRGRtvls\nmZvmvPNmlNJPJzzmgNvNgdqqdBSpfHBqSsHqHfwpsffq\nnhDQDrwLrVVnqfGnsBGBGGsH\nVjCDMhbDjLjtFhtLhLhQjNZcZPwWWcczmvglgJJN\nwwqnwZGGZqqMpMprpZqwGlLDtNDffdBdNVBmNGBN\nTSTchTFbRLfLmVhNDm\nSCLRvJQvRFTSRjqMqPZrZnrzZzjp\ncJfqGjgGJcsgsPnghgBm\nFHHbQQHLWLbPQThqQQRnZs\nlLLMSCvrlFMwlSlFcNwqDVVpJcfjzVDf\ncRdRDhsDFzPztwJdGP\nCVqpCqCgSNfCSQBpjtBwtlBBHLlmGjGG\nqfQfCVQfgQnVNpQCMqfcrFrwWDhrDnsvcRDsbc\nnFWWzqWZQSqnJzNJzslJVsdV\nvBBvsLvbBmBmRlGTNJJvRRTD\ntBbpmmPwCmHpMHHMrPCCcSnZSgcFcZgWFscSfgth\nLLssTJrqrpvrvvpJvdjggMlgzVgVggPlFPqz\nHwZwCZfHNtbMzjgVnFPC\nRSttfRwZDtBcZwQMQdrQsdTBQQmW\nlJnNhMJqljlNhSrdWlGGGQHwwH\nvbTpbCsTFCTmbSmcRfVCfRpwcPdwWQQrdwHwBHrPdwrLLB\nsVTmDfmCTVmJjgSzzntDtt\nDQtMjZHZHvMbwwTSpqLtpJ\nFzVFlsNdVczWPzWcslVfSLqLsqJpSwwsJswLrf\ndNFFWcmzWFGLWcdcFgvZvvRHQvjMHDMBGD\nMVPTmPvbMgrTmmmmMRMvPvBwFGhhDCdFFwLCLdJhDGFRhG\nfqqWfpZWzWsDwhwdhwqGLD\nZWSSftStnnplcQLSbVMBvTbrMlbrBvvl\nFSsHDmtFLbbFbLGg\nvrvzTzWzzzvppzSzTMnfTggjVgbgjbLjgPPnbGbVGL\npdMwrBpfwfSMTTWdMTpBDCBtmsmltslcBDCshDHs\nRgbmfGtmRVgLLSVSnSrWWSHhnh\nccTvlvNppsFnbFnhnWnPHJ\npqNjDBjNNjvpZfmtjbCLbCmb\nqsSVpSVfWqgNrVtWptpmSfqbPQljbHPHlDnljRSlwSnwQn\ndcGBrMFMdLTGGdlwDwMRHwwMbjHP\nCFBvhFhTLFCGvFchChBdBTJtsNpWqfVgtszprmVWNqNgvV\nsjsTgNSNqSjgMmVPmmmrpH\nRftCcWddRCZfPtCfcQZdcZDcrBllBFpVHprHWlHHpHJJmlFp\nthPZRtLcDRdDCTTsqbnwjhvNjq\nTQPtgfgdPcdSQhjwHhHBLS\nRrqCqVVbJmVRJmsrzmJpWljlSHLSBwSSRWllWv\nCVrDNbHrJHVMCbrDJsdFdFcPFZngMfFdTPfP\nNNlZgndqmGVGGVZNWQmWmbhbbhpbbhtCbhtgCpCtMF\nTHfLPTzwJTJrvHRwwsbFbhfbMCpphVtBbB\nRjrvzHLzPDvLzPHrTJVrwPndZQNlDZGndZWDdNNcmlQq\ntjDsjDGtTjVVbQVCggvrbg\nqrWWRBllRFrdlSMCdbSJCP\ncZcncRnhphpZWRNtrmsrGpHffmwH\nqpRjdcqTcMbbMRTwtnplnwnhPzhBhw\nFSFLvNrsPNrsGSLsrFSGfnwBQwZnZwhQQLwwQhnn\nsWNVmVmCFNWGsCrrjRTmMjRjPRqgJqJg\nsVCnzVpmFpVSnNFCmnmzwRFDWDdMllDccMdwDMjWjWlWjg\nBJbPJGGGHPZqZQbpMlWWMWlBljjjgDjh\ntGQPpZtfTPpqrHsVLSzmRNLtSFsN\nWCDlBWWlvMFWlQWpmSZdZnNmGfJZFZ\nLqjTjgtjPcHTTJgLThztcLTLnHnmdSpZdpdffnmZSppfGpSn\nPtzqzjtqJgggzhqqccqhrQMsMvMwrCwMlBvMwvvsvs\nNMsJfsHTMVbjnLnVsC\nhtWllhmZcWDWBwhZPcmpVRjnVMRLCCjLFpCwRb\nPmZMrBtcPmZWhzDWBtMmJQdddHfQGNSqHqQGGTgr\nNmfnnsPlHnGqnlsNNmRPltRLvrhvrSGJSJjvFFFSSFJLhb\nPzQZccVPVwgPjrJSJjhFFpQr\nTdwBgdTVwzdwzlmNfRqPmqqTql\nBVLLBPmPmWBlMlLJnJlBlFQVgdRDdRZRZHpZjQzdRdZQdzQZ\ntrGTsfbTTgHZptzSZW\nfsfTNcCqqNhhVhVFVhVBWLLB\nLJwgJNfbCvwCJCwBCCNhhHmGHWWSMWmWmbMmTmmGdS\nlzRnnltsstZzzRTfHtHWHGWftfHW\nZFFzVFqzqlFcZscZpRZsNphjhjvjfgJhQgQvwvhC\nHHzcFNcHFjhjZjlrghLL\npMZJptpZWCmpttRMCWnnDnBGGDLhlLQrhl\nMJsMCTZTTpTJRmMCJzfNsNcfNHqzvvfcww\nZDtllsDlVsrQBqQqRfWl\nwvJgpPhhscgvpJFNrRjRrWRjqrRjdjRv\nzpsNzCsNCJCCPPHSLzznMnDSLGLM\nrfrJjFWrwjpnJjjjfrjJJnFVTgTggRWRRRPPLQgCgQcPPT\nsSNbSvqmsSZDZZBtNTTPGgMLMRVcgPCMRb\nzZDZzNNSmrfpjFCjzj\ndbbNJPBbbrFqNqttqrGbqDcmDQRmFmwcwSnQSDcpwS\nZMMTsHjzLlLcnSVwpRRQ\nhZTWjWvTZzTTWhszfwbJhrgJqtBbJGdqNPqt\nrrqgHrgtcHJRRjWZlRvnnWBn\nQbhVmdFppwbdjnMvlnBwMWZP\nTpFDdVTFTDfhHfJcSJSzGZGf\nsqNTNZHsHjjFBBwJMMNMcCJD\nWGLQPjfWfQWPWmtLSRRRLwBJDbtCCJJCbbwCMBbMBc\nRnPdLQfPLRdndGGRvfjlgdrTTgTsrgTrZFzF\nBfHbjVVqSBFfMSlCLCDrGSQssvlr\ntTpnnzpcPnwzhcnJTDtTPRprGlRGGGCWlQsWvrlvrQGQrC\nDPwhghDTpPVHqqdgZbZq\nZzPqfGPtRtqfqPbqfGgGZbrhMjmjBCpHpHNCmHtHjmBHnj\nQJwllvFWwDvnwCBBzjwwpC\nccJLVQzWFJvVJlVbgrZZLZLRRPSgdr\nrBGbLbnTfnZrQbTnHldqsMmHsqlsWfMd\nJcJjCCPzPtjCNHdlGGMlll\njjgpRRvcGbwpThVppT\nttDfjtqfjtpTWWwfTbtlWccNGRSZNGPGhZGhGhcwRh\nLbCrHdvzLSSHmSRNmc\nJCsBvrvBLzFQbbvlVVnpQpDtWlDqfq\nvvdvJBfvdTvRBflBJPNmmffmgPCMwDgsss\nrFjqLnMcnqrrtMLtjNgCPCsNzzgsPCGFNs\nVqLqnLVZqjMZqWnrVtWlZJJSvHvBdRSvBdRvvJ\nzZBDzgQQZLlcglzjrCrCMFjGZbMsHm\nPnnJVRfttTtwVnnVFGHVsjCFCjrsMM\nwPRpRpRnNTpPNlBdQQDdgDNMhN\nbNQpFpnwgtDHpbnhWtffmfmhvhhfsZ\nLcdLdwCLPPSVSqqwZGhWdJhGJZhlGlsm\nTBwSLPSPVRSVqSVqVrcnpMDDngMgnQpbRQFDNH\nvPSvBJZSSdJgpJJZBDGDGrdqGdllGrGDrh\nHMtsltFlRVVFtlscRjjMcsWwWChWmrnwDWGwChmjGCWq\nMQHNlTVHNVHpbbpbTvvBvf\nVsbPMwhbWhzdpzNNggnBcTBWNngQ\nRmtZZFZqSjqVHmGQNcBHNLGLGHQH\nJjRClqCjZlDZmqSqljFZZqRCvsvPfshhMdwsDwbVwzMzhffb\nbfGtRgfDtVmsMzTbmz\nLjGZwQLLdjFdHLNMhmzBzMNHNmzN\nwjQLCFvnnQGdZLGWSjdqWDfPlrRpqRDDRqrpPr\npqnBZqjCNCqQqmllpHGMGdTfML\nPsFgrRvSPsWTwWWQwGHLHW\nSrvgsFbrrPJJFsrFPtFSCChBDQjqCqtNhDqhCqNC\nRJZRWZWMWZPZffRCPWMdRdfQQQjJzHQsssjrSQFVschVHr\nNgpnDgvGTNTVFHFFjVFF\njntvgljpGvlnbLtLbBvnLRPlCCwwCfRqMCCqqqddqw\nPFBMVDSVPHMTThtMtSBMMVNbQprHbNRgNRRgLnvpnjnN\nscGcrcwlswdGlcqvbQgnnpQnqLjnpp\nffwswWzcmlcWWsmcZhrDFrZMFZBMFzhM\nLMdZGqdRSSZmCZMRfQjnggvlvggRcznz\ntjjFhBrtpthpslcvvlcQzFnFvQ\njrhbjtpJtbZqCLdWLq\nHBGBfBttZzbGbljPdpFddFqRmqRzRN\nJDWghDDSDqmmDDpc\nCLvgMvChCvLphCTSShhMhQsBbfTfsGsrBfjfrljrZZff\nRgHgDqDzqQqgcdHqcZGTNlGffGBDGZBTGZ\nLFLPWsmvrbwhwwswrTlTTCBNGFfGlNJZNS\nvhrLnvhNmWvMsrvwqMdRcptQtztcjptz\nsLMLsThhjgqLlsnsLgTLtMFcRbcPcJSwJbbSbtSWScSt\nfvrjjDjvNprdPwwJCCSrWPFP\nvfZdGzVzfvGGVGpBjnnMglTsgZlqsMlM\nTCVMfCfBnHHfLLPFWb\nGgQlGJzNzbzHcHHLlcPLHL\ntQbNQGgRZZCVtVMZ\nQFFMzwjwngsvsBjGGJWbBbBWbB\nQdmVDmVDWRPWVPVV\nQHtHSdDpLQCCSHrtqrdrttDfLgvnFvFghNszzwgngFwsNF\nRzzTNpSRBzSBVpSRlHNSHBSSGPcLNGtjhPPcbcGhPPhcrnct\nCCmmCwwdfFJqDmdwsddhsmvdcMbLfcftttbPnjMPbcjPMPbP\nmdZQmvssFdqsFZvsZQmvDvmWzgQBWTRzTzHlppWRglHBQh\nVWmnfQWzWWnHWMfmmMVNMfWjtBtBNSNSrlStlpjJBBlgBS\ncZZvbwsZsbbZvvscCRdFTTTQrBStdBJgSdhjgBjBjJjpJJ\nwCFTCbZbFwwCTvFTwsPGccMzMDWVWfzLGmqHnnDHGLQL\nsNQQHbbhdlpdrQllqpsqSpGjZDZGgDnVcnjjnnDZ\nWWRLGFvJBJPvzzWjnTncDVZTTPgDff\nFLRLGRFRJLBWJmJzMRLCvldrMrbbltdhQQlNqtMbsb\nHZllwlZSlSZwhvmQjcZhTqcT\nsPzzdgpszpzsBdvvMccvcqPThjhM\nJDdsDspLzsdzBgVdBGBzCLlwbbwWSnlnnWffHwJcNlHw\nnzCTCnpqJqfCnvvjZjWjPcZrmcmZfW\nGNdwgVjwRdRglMrPWLPWZWcNWW\ndVblgtRwQgSGVBldbQBbBRJnQJTsJHTqnzzJFpjvHnnn\ndqpQQrdqQpLfqcGSdggQdgRMmwHBMMBVNRNDFFBDBgNt\nvTzsnZCnlCnshbPlvZJbBzVmmVRDNwtHFBwMDVBR\nlJCshjTJbVqfVdjjjG\nWlLCJlHLcZcJWcWZJnLHnPqlFtSthTnFNThVtNhVhvNVzVtF\nQfbgRsspfDRsgfjqqRRpDbSNSTFzBbTbhttVBhVNBzzT\nfwgfRdpdfQDqgPHHZJZCcdGddH\nsbrbmVmfddzJntZZtwtMMf\nPvhwPRlvvWhFvSRhpFMMJGMFppnBTBGJ\nRPlCCLDPDClwHbrdzsdNLzgs\nHZgqtgbqRZvzwzCh\nBFqmGfrNLQfhzJWBhRJwJR\nLFqFQjrcrcqFNMmMdHggntDPMnsDbn\nNmWmPblGnnTTNlFGPmNWfwdchdlHdBdwcfCfZppZ\nrzqzRjgVrJrzzcFdqdCBFBhZhH\nVDRsRMjRJJrQsJPTGFNvsbnsnLGm\nnrbrBLTffjNRzGQSJHJQGT\ntcZqMcppCmHRQPGGCG\npMDcZhpgcpFDfrwNDDrLVjGj\nLWlmlmWqvrBMWWBlmjLThBrfPJZfZZCwPCJJwPCTcggCsd\npSbRHbzpHDVFRQRfPdfnZswgcJcppp\nSzRNGbzSWNPLWqLv\nvqslblpspsvqBFSqcrrZZDdTfFPHccrf\nGWRhWmjwhRcQdCDrPjDP\nmcWLVnnWJgGRzVSsVSpSSptNpMvb\nwHTPfdTvHlPHGpdvvTddGfcJLLWWwWWcCWrqrVMWCVLL\nzhsSNZhnshNSnvZmvsCWWSLrVMcrSCLWJcrq\nsnDnshmNsjnTdHPfDGvdDT\nCfrnFFMnnsRNrNCwFCrdssgqgqvVZvZqlTWBNWZqlJBW\nhtDhDLhwPWWBqTghgB\nDPLPzHDtSPStjLGLtzSMwbdMdnCHrRdCFsmfnR\nnBNWCvJmVPNnCPNDJWbtmSwqTttcQsSqtqTjQQ\npMflzLlffRRMRdFlflpLddGdsTjwHqzcvwTqtsStQQjtwwsQ\nZhGlphlpvvLLfFGvMLhfrfWNJNNPVPbnPhnDgDbDDNbJ\nZCpCmVlZvlpBBwvvMCrJhrfhMfjjWMSG\nqhstFzFFqzHGzNfSMJSGzM\nQnHRPRgRQPtPhtnDsqsbDQPBlTcpBwmVmTvbwdwBTVZVpl\nPHmqHdddqBWMmTvMvTGMBWPdwhssnnHlhgsNwhwNHQzwrswh\ncSbVcDLtbfLSFzhlhJswgtrsww\nbSLlFLFFLDZVLpZVjFLdPMdBBqGGPmmqWGdGjM\nFQCnQwFRbnrSfgQgwFRCnswmPLpMppPdMMllpLMptMLldPSZ\ncJhhJcJVBJjhfHDvJqThvVDcpdGGqdZGdlltpqWdMqpdGWtG\nHhzTjJBzJTvNJHvzvvNBzBFnFCNCbCwrbnRbgRwfwQsg\njRzDgbDDQDgVqqDGsjttNdwqNJZNwNdTWrpB\nMHvvvlSHFllMhhMrpWBJtlWdpJrTwZ\nmFcFFHmCmtcvfvFFHHLDGnRVzjDgnmgmnzGgGg\nJJhDpDdmsJJdgmhrpPjGjFLPPSNpjL\nWbznbRGnPfrfRSrN\nWqGnnVGVMGHtWTCgJvZHggBggZCg\nwlrPQtZQvwrzlvNfZLMZBjbbqjqLbSBjTg\nPGJDVdsdhsPVPjbTcLcGLgjqbM\nVPDRHWRdsRQvpfmmlw\npvTZTSpTZvGGphNvvbDpdrMqrjlWdPqqjWdldNrd\ngmmJmsQfJgcRQJQJJncVQjMWllSnqljqBlPPjPHHHH\nQVJQRVcwmJcchwpSZLwGbSZZ\nzjrDMWcjDzQjDlWrnqqRBRNhBJRBhBJqnf\nTTGPPdgGLwdHGwGPTgLbbvhHtRRNRRSfchqRvSqHRJ\nTZTccPpdZwPQjllsspjVzD\njHLHhHFRjhcblDRRWbWTdtppLTntTnMmGLMvTp\nBBQBgBBCrrgqJqTtMZMpngdtpvpG\nQJJJQrsVsQQfQVPCNqsNSjHdhhdRHDNHFHFclh\nRbCLnvdtnLRLRbmLPpHdQCvmNJpJSZSJlgDzglGlzcclcDGD\nqBBwMjfsFMjsMbfWbwjlzDZlcWclJczgNDGNDl\nwqjhrwwhhCvbQPrRnC\nvpWDDDWZQQNGllwHlwWVGj\nLCPdqdcdtsvdsCtsddvmVrVjjrBwHlmswmBnmw\nfLfvSgvMfdCPqzZNThfNNpTJJQ\nCVVVLbNVmGNQbGbGHHbHbvdwgQlwJDTFgJQdDZDJFD\nssWBsBWrjSzWrPtBjnSCTwvFZlDjwZDdgwTDwggv\nnntPBqBrPsBfnCRCBWzCVcGVHMLNcbHLNmHqGphp\nsbbwwzdsbqQQbQnnNbPNGbznHHRdLTggMVHFVvRZTRVRHMZF\nmWffDWfflBpfmcWjWrrJVvgRLlMZVVhMFFTlHhMM\nrJJCctmjcfvzsqsqbtbqPP\nHGWjHWzVctQVcJVtjvRsvLTddqDDDsjRLg\nbbMnlNChZQLZhdDs\nSMMMMMMNmMllSlrmCczGcVzBcGWFBQGcrt\nVwQlqcLfdLGqdqDjjgZrjZBdttjd\nzSPPPJzJGjJjZrCBDt\nWMTMsTWsccsvGGwH\nhZvbQrjTTZjZcjWNrjnQrcTRpGMqcRfRRGzHfHfpfRMqRz\nmDJlFmwCVVwbCVbPBRLMMLpRLwRLHqpR\ngsCmgJsPDCtCVlvbhgQjhgQbnQbd\nfSgbhhGPGJGhRDmlhhHcHDBH\nLsMwQWFswsQMsQMvjslcBcDldBTWfDcHRRdl\nZpVFwLQwVLQvCVsMjrJbbCNPbzSJtPbPPf\nVDzWMCpfCcCRDzqDzqNnvLZnfntHQnPPLQlt\nsJmdbTBdmmGhFhhbJNNQlJnQlQLHPZNn\nsdwmwsdrmMRpDRMLcw\nJpWmSWpCnCbJBZHZVldbdfZf\nrgdrgNdrjgNPrMjwTssrPdfDZqsVfQHDFlQDDHQVsZfB\nTRPdNNLgjNwrRTrJpppzCmzmCLSnvS\nQbtQJHQmbmfmBRvbQRzBvldqcFljsGcFdGdvsqqGls\nChCPWhDhWZWJVnZpCNChhVDcMcDdcdgGscjgFjGFlsjjGq\nWZNTWNhNZfJJbTJTmR\nCHGCHFcZvCrchrZrhsVtsBQjMstfZMMBgg\nNNqwDLmDjJgQBmVQ\nwdWLLTgWRTWcCcbrHCHhGW\nbTZZvNjNjLgTCHcWhccfhWJdhvnc\nmnFFmPGSwRPShzVPPWPdhhzr\nFRtBFGBMFQFttRwtZgTjCTnQNbNLjTCH\nbJSqrSpDJbSNbFjSFCfPWGcwGWPrcTCfwr\ntRtLhDsvhQZlHRhRtQQnCnCcdwCPwTwdGcGP\nHsHvsmBZvmvsmBhHvLssVqDSNgFMDzgbbDVJzbpMVq\nnSSDHRRRQRBCLCQC\nqGmfPzGmGlrrrpfrqlzrJtLvBlhQbSCvbtCtlFhLFC\nzzpmqqJJVVfJfPfMpfdHNndsNwDSMSDDNcsc\nCscQsVMhCsMsMHhhVthtwmgZNRqzWLBRLRLmBWmZWBND\nJQJdddrjrLqBgDBq\nQbFlTffpMbMnsPCh\ngDdbVbVDddDfVfWQfBRLQZsZLRQQ\nFCCTrGCMStwGHTtTWLQhLZrlRssRhRhp\nFSHqtFTmFwmCsSwGTHtMTSdjjcdnVddgzmbVmjmndbbD\nJtBBMcLWLdfFLhMttcWWhfWLrTRGFsbwTmRGwmwbbCTGGsbD\nPzQpSQQQvzVvpzHqjvNvQSvGRmmTDVRDmsGsRGsrcDcDGC\ncQPHSPvPvZHqcZjzpZjnZNtWlLdtldJWfnfhlJJtLdMg\nnPPssTBnMJPdtHPVHtRhpv\nbSSgGFWDgWwDFFlmWlcShqdpRqpVcHvvnqpvpRHd\nbGFnGljgSsjBCTBszz"
var alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func strSet(s string) string {
	t := make(map[string]struct{})
	for _, item := range s {
		chr := string(item)
		t[chr] = struct{}{}
	}
	var x strings.Builder
	for chr, _ := range t {
		x.WriteString(chr)
	}
	return x.String()
}

func count(seq string, occ map[string]int) {
	for _, item := range seq {
		c := string(item)
		if val, ok := occ[c]; ok {
			occ[c] = val + 1
		} else {
			occ[c] = 1
		}
	}
}

func Part1() int {
	var total int
	for _, pack := range strings.Split(input, "\n") {
		occurrences := make(map[string]int, 0)
		m := len(pack) / 2
		first, second := pack[:m], pack[m:]

		count(strSet(first), occurrences)
		count(strSet(second), occurrences)
		for key, val := range occurrences {
			if val > 1 {
				total += strings.Index(alphabet, key) + 1
			}
		}
	}
	return total
}

func Part2() int {
	var total int
	var chunks [][]string
	var chunk []string

	for index, item := range strings.Split(input, "\n") {
		chunk = append(chunk, item)
		if (index+1)%3 == 0 {
			chunks = append(chunks, chunk)
			chunk = nil
		}
	}

	for _, x := range chunks {
		occurrences := make(map[string]int, 0)
		for _, item := range x {
			count(strSet(item), occurrences)
		}
		for key, val := range occurrences {
			if val > 2 {
				total += strings.Index(alphabet, key) + 1
			}
		}
	}
	return total
}
